# Generated by Django 5.1.6 on 2026-08-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_consolidate_name_and_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي'), ('4', 'أولى إعدادي'), ('5', 'تانية إعدادي'), ('6', 'تالته إعدادي')], max_length=50, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='year',
            field=models.PositiveIntegerField(default=2026, editable=False, verbose_name='السنة'),
        ),
    ]
